# Base image
FROM node:20-alpine AS base

# 1. Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
# ⭐ Key Step for China: Set Alpine Mirror for faster install
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

RUN apk add --no-cache libc6-compat openssl
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./
COPY prisma ./prisma/

# ⭐ Key Step for China: Set NPM Mirror for faster install
RUN npm config set registry https://registry.npmmirror.com

# Install dependencies
RUN npm ci

# 2. Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ⭐ Install OpenSSL for Prisma Generate in Builder Stage
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add --no-cache openssl

# ⭐ Generate Prisma Client for Linux (Alpine)
RUN npx prisma generate

# Build Next.js
# Disable telemetry during build
ENV NEXT_TELEMETRY_DISABLED 1
RUN npm run build

# 3. Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# ⭐ Install dependencies for Runtime (OpenSSL + Baked-in Tools)
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add --no-cache openssl

# ⭐ Bake in Prisma CLI and TSX so we don't download them at runtime
RUN npm config set registry https://registry.npmmirror.com
RUN npm install -g prisma@5.22.0 tsx bcryptjs uuid typescript @types/node

# Fix: Ensure global modules are findable by node/tsx
ENV NODE_PATH=/usr/local/lib/node_modules

# ⭐ Persist DB: Create writable directory for SQLite WAL files
RUN mkdir -p /app/data && chown -R nextjs:nodejs /app/data

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Copy prisma for potential migrations
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma

USER nextjs

EXPOSE 3000

ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

# Using server.js which is generated by "output": "standalone" in next.config.mjs
CMD ["node", "server.js"]
